import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { RefreshCw, ShieldAlert, CheckCircle, AlertTriangle, Ban, Lock, LogOut, Settings, Send, Download, Trash2, Pencil, Power, Search, Radio, Bell, FolderKanban, BarChart3, Plus } from "lucide-react";
import "./style.css";

async function api(url, options = {}) {
  const res = await fetch(url, { credentials: "include", headers: { "Content-Type": "application/json" }, ...options });
  let data = {};
  try { data = await res.json(); } catch (_) { data = {}; }
  if (!res.ok) { const error = new Error(data.error || "Request failed"); error.status = res.status; throw error; }
  return data;
}
function Badge({ status }) { return <span className={`badge ${status || "unknown"}`}>{status || "unknown"}</span>; }

function Login({ onLogin }) {
  const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e) { e.preventDefault(); setLoading(true); setError(""); try { await api("/api/auth/login", { method: "POST", body: JSON.stringify({ password }) }); await onLogin(); } catch (_) { setError("Password salah atau session tidak valid."); } finally { setLoading(false); } }
  return <div className="loginPage"><form className="loginCard" onSubmit={submit}><div className="loginIcon"><Lock size={26}/></div><h1>Domain Radar</h1><p>Masuk ke dashboard monitoring.</p><input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="Admin password" autoFocus/>{error ? <div className="errorBox">{error}</div> : null}<button disabled={loading}>{loading ? "Checking..." : "Login"}</button></form></div>;
}

function Dashboard({ onLogout }) {
  const [overview,setOverview]=useState({}); const [domains,setDomains]=useState([]); const [results,setResults]=useState([]); const [alerts,setAlerts]=useState([]); const [projects,setProjects]=useState([]);
  const [rankKeywords,setRankKeywords]=useState([]); const [rankResults,setRankResults]=useState([]);
  const [domain,setDomain]=useState(""); const [projectName,setProjectName]=useState(""); const [bulk,setBulk]=useState("");
  const [projectForm,setProjectForm]=useState({name:"",notes:""}); const [rankForm,setRankForm]=useState({project_name:"",domain:"",keyword:"",target_url:""});
  const [proxy,setProxy]=useState({name:"",provider_name:"",proxy_url:"",proxy_type:"http"}); const [proxies,setProxies]=useState([]); const [notice,setNotice]=useState("");
  const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState("all"); const [projectFilter,setProjectFilter]=useState("all"); const [autoRefresh,setAutoRefresh]=useState(true);
  const [settings,setSettings]=useState({check_interval_seconds:"60",retry_confirmations:"3",status_keywords:"internetpositif,trustpositif,nawala"});

  async function load(){try{const [ov,dom,res,px,set,al,pr,rk,rr]=await Promise.all([api("/api/overview"),api("/api/domains"),api("/api/results"),api("/api/proxies"),api("/api/settings"),api("/api/alerts"),api("/api/projects"),api("/api/rank/keywords"),api("/api/rank/results")]);setOverview(ov||{});setDomains(Array.isArray(dom)?dom:[]);setResults(Array.isArray(res)?res:[]);setProxies(Array.isArray(px)?px:[]);setSettings(set||settings);setAlerts(Array.isArray(al)?al:[]);setProjects(Array.isArray(pr)?pr:[]);setRankKeywords(Array.isArray(rk)?rk:[]);setRankResults(Array.isArray(rr)?rr:[]);}catch(err){if(err.status===401)onLogout();else setNotice(err.message||"Gagal load data.");}}
  useEffect(()=>{load();},[]); useEffect(()=>{if(!autoRefresh)return; const t=setInterval(load,15000); return()=>clearInterval(t);},[autoRefresh]);
  const projectOptions=useMemo(()=>Array.from(new Set([...domains.map(d=>d.project_name||"No Project"),...projects.map(p=>p.project_name||p.name).filter(Boolean)])).sort(),[domains,projects]);
  const filteredDomains=useMemo(()=>{const q=search.trim().toLowerCase();return domains.filter(d=>{const p=d.project_name||"No Project";return(!q||d.domain.toLowerCase().includes(q)||p.toLowerCase().includes(q))&&(statusFilter==="all"||d.global_status===statusFilter)&&(projectFilter==="all"||p===projectFilter);});},[domains,search,statusFilter,projectFilter]);

  async function saveSettings(e){e.preventDefault();const saved=await api("/api/settings",{method:"POST",body:JSON.stringify(settings)});setSettings(saved);setNotice("Settings saved permanently to Neon.");}
  async function addProject(e){e.preventDefault();await api("/api/projects",{method:"POST",body:JSON.stringify(projectForm)});setProjectForm({name:"",notes:""});setNotice("Project added.");load();}
  async function deleteProject(name){if(!window.confirm(`Delete project card ${name}? Domain tidak ikut terhapus.`))return;await api(`/api/projects/${encodeURIComponent(name)}`,{method:"DELETE"});setNotice("Project deleted.");load();}
  async function sendTelegramTest(){setNotice("Sending Telegram test...");const r=await api("/api/telegram/test",{method:"POST"});setNotice(r.ok?"Telegram test sent.":"Telegram test failed. Check token/chat id.");}
  async function addDomain(e){e.preventDefault();await api("/api/domains",{method:"POST",body:JSON.stringify({domain,project_name:projectName})});setDomain("");setProjectName("");setNotice("Domain saved.");load();}
  async function bulkImport(){await api("/api/domains/bulk",{method:"POST",body:JSON.stringify({text:bulk})});setBulk("");setNotice("Bulk import selesai. Format: domain.com, Project Name");load();}
  async function editDomain(d){const nd=window.prompt("Edit domain",d.domain);if(!nd)return;const np=window.prompt("Project name",d.project_name||"")??d.project_name;await api(`/api/domains/${d.id}`,{method:"PATCH",body:JSON.stringify({domain:nd,project_name:np})});setNotice("Domain updated.");load();}
  async function toggleDomain(d){await api(`/api/domains/${d.id}`,{method:"PATCH",body:JSON.stringify({is_active:!d.is_active})});setNotice(d.is_active?"Domain paused.":"Domain activated.");load();}
  async function singleCheck(d){setNotice(`Checking ${d.domain}...`);await api(`/api/check/domain/${d.id}`,{method:"POST"});setNotice(`Single check selesai: ${d.domain}`);load();}
  async function deleteDomain(d){if(!window.confirm(`Delete ${d.domain}? History ikut terhapus.`))return;await api(`/api/domains/${d.id}`,{method:"DELETE"});setNotice("Domain deleted.");load();}
  async function addProxy(e){e.preventDefault();await api("/api/proxies",{method:"POST",body:JSON.stringify(proxy)});setProxy({name:"",provider_name:"",proxy_url:"",proxy_type:"http"});setNotice("Proxy checker saved.");load();}
  async function deleteProxy(p){if(!window.confirm(`Delete proxy ${p.name}?`))return;await api(`/api/proxies/${p.id}`,{method:"DELETE"});setNotice("Proxy deleted.");load();}
  async function manualCheck(){setNotice("Manual check running...");await api("/api/check/manual",{method:"POST"});setNotice("Manual check selesai.");load();}
  async function addRankKeyword(e){e.preventDefault();await api("/api/rank/keywords",{method:"POST",body:JSON.stringify(rankForm)});setRankForm({project_name:"",domain:"",keyword:"",target_url:""});setNotice("Keyword added.");load();}
  async function checkRank(id){setNotice("Checking Google rank...");await api(`/api/rank/check/${id}`,{method:"POST"});setNotice("Rank check selesai.");load();}
  async function checkAllRanks(){setNotice("Checking all ranks max 50 keywords...");await api("/api/rank/check-all",{method:"POST"});setNotice("Rank check all selesai.");load();}
  async function deleteRankKeyword(k){if(!window.confirm(`Delete keyword ${k.keyword}?`))return;await api(`/api/rank/keywords/${k.id}`,{method:"DELETE"});setNotice("Keyword deleted.");load();}
  function exportCsv(path){window.open(path,"_blank");} async function logout(){await api("/api/auth/logout",{method:"POST"});onLogout();}

  return <div className="app"><aside><h1>Domain Radar</h1><p>Multi-checker domain monitor</p><button onClick={manualCheck}><RefreshCw size={16}/> Manual Check All</button><button onClick={sendTelegramTest}><Send size={16}/> Telegram Test</button><button onClick={()=>setAutoRefresh(!autoRefresh)}><Radio size={16}/> Auto Refresh: {autoRefresh?"ON":"OFF"}</button><button onClick={()=>exportCsv("/api/export/domains.csv")}><Download size={16}/> Export Domains</button><button onClick={()=>exportCsv("/api/export/results.csv")}><Download size={16}/> Export History</button><button className="ghostBtn" onClick={logout}><LogOut size={16}/> Logout</button>{notice?<p className="sideNotice">{notice}</p>:null}</aside><main>
    <section className="cards"><div className="card"><ShieldAlert/><b>{overview.total||0}</b><span>Total</span></div><div className="card"><CheckCircle/><b>{overview.working||0}</b><span>Working</span></div><div className="card"><AlertTriangle/><b>{overview.warning||0}</b><span>Warning</span></div><div className="card"><Ban/><b>{overview.blocked||0}</b><span>Blocked</span></div></section>

    <section className="panel"><div className="panelHead"><h2><FolderKanban size={20}/> Projects</h2><button className="smallBtn" onClick={load}><RefreshCw size={15}/> Refresh</button></div><form onSubmit={addProject} className="projectForm"><input value={projectForm.name} onChange={e=>setProjectForm({...projectForm,name:e.target.value})} placeholder="New project name"/><input value={projectForm.notes} onChange={e=>setProjectForm({...projectForm,notes:e.target.value})} placeholder="Notes optional"/><button><Plus size={16}/> Add Project</button></form><div className="projectGrid">{projects.map(p=><div className="projectCard" key={p.project_name}><b>{p.project_name}</b><span>Total {p.total}</span><small>OK {p.working} · Warning {p.warning} · Blocked {p.blocked}</small>{p.project_name!=="No Project"?<button className="smallBtn danger" onClick={()=>deleteProject(p.project_name)}>Delete Card</button>:null}</div>)}</div></section>

    <section className="panel alertPanel"><div className="panelHead"><h2><Bell size={20}/> Alert Center</h2><span className="muted">Latest 100 alerts</span></div><div className="alertList">{alerts.length===0?<p className="muted">Belum ada alert.</p>:alerts.slice(0,8).map(a=><div className="alertItem" key={a.id}><Badge status={a.new_status}/><div><b>{a.domain||"Deleted domain"}</b><small>{a.old_status} → {a.new_status} · {new Date(a.created_at).toLocaleString()}</small></div></div>)}</div></section>

    <section className="panel"><h2><BarChart3 size={20}/> Google Rank Checker</h2><form onSubmit={addRankKeyword} className="rankForm"><input value={rankForm.project_name} onChange={e=>setRankForm({...rankForm,project_name:e.target.value})} placeholder="Project name"/><input value={rankForm.domain} onChange={e=>setRankForm({...rankForm,domain:e.target.value})} placeholder="targetdomain.com"/><input value={rankForm.keyword} onChange={e=>setRankForm({...rankForm,keyword:e.target.value})} placeholder="keyword"/><input value={rankForm.target_url} onChange={e=>setRankForm({...rankForm,target_url:e.target.value})} placeholder="Target URL optional"/><button>Add Keyword</button></form><div className="panelHead"><span className="muted">Uses Google Custom Search API. Page = position / 10.</span><button className="smallBtn" onClick={checkAllRanks}><RefreshCw size={15}/> Check All</button></div><table><thead><tr><th>Project</th><th>Domain</th><th>Keyword</th><th>Position</th><th>Page</th><th>Last Check</th><th>Actions</th></tr></thead><tbody>{rankKeywords.map(k=><tr key={k.id}><td>{k.project_name||"-"}</td><td className="domainCell">{k.domain}</td><td>{k.keyword}</td><td>{k.last_position||"Not found"}</td><td>{k.last_page||"-"}</td><td>{k.last_checked_at?new Date(k.last_checked_at).toLocaleString():"-"}</td><td><div className="actions"><button className="iconBtn" onClick={()=>checkRank(k.id)} title="Check"><RefreshCw size={14}/></button><button className="iconBtn danger" onClick={()=>deleteRankKeyword(k)} title="Delete"><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{rankResults.length?<p className="hint">Latest rank result: {rankResults[0].keyword} · {rankResults[0].domain} · position {rankResults[0].position||"not found"}</p>:null}</section>

    <section className="panel"><h2><Settings size={20}/> Settings</h2><form onSubmit={saveSettings} className="settingsGrid"><label><span>Check interval seconds</span><input value={settings.check_interval_seconds} onChange={e=>setSettings({...settings,check_interval_seconds:e.target.value})}/></label><label><span>Retry confirmations</span><input value={settings.retry_confirmations} onChange={e=>setSettings({...settings,retry_confirmations:e.target.value})}/></label><label className="wide"><span>Status keywords</span><input value={settings.status_keywords} onChange={e=>setSettings({...settings,status_keywords:e.target.value})}/></label><button>Save Settings</button></form><p className="hint">Setting tersimpan permanen di Neon. Bulk import support: domain.com, Project Name.</p></section>

    <section className="panel"><h2>Add Domain</h2><form onSubmit={addDomain} className="domainForm"><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="example.com"/><input value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="Project name optional"/><button>Add</button></form><textarea value={bulk} onChange={e=>setBulk(e.target.value)} placeholder={"Bulk import, one per line\nexample.com, Project A\nexample.net, Project B"}/><button onClick={bulkImport}>Bulk Import</button></section>

    <section className="panel"><div className="panelHead"><h2>Domains</h2><button className="smallBtn" onClick={()=>exportCsv("/api/export/domains.csv")}><Download size={15}/> CSV</button></div><div className="filters"><div className="searchBox"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search domain or project..."/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All status</option><option value="working">Working</option><option value="warning">Warning</option><option value="blocked">Blocked</option><option value="unknown">Unknown</option></select><select value={projectFilter} onChange={e=>setProjectFilter(e.target.value)}><option value="all">All projects</option>{projectOptions.map(p=><option key={p} value={p}>{p}</option>)}</select></div><table><thead><tr><th>Domain</th><th>Project</th><th>Status</th><th>Last Status</th><th>Last Checked</th><th>Active</th><th>Actions</th></tr></thead><tbody>{filteredDomains.map(d=><tr key={d.id}><td className="domainCell">{d.domain}</td><td>{d.project_name||"-"}</td><td><Badge status={d.global_status}/></td><td>{d.last_status||"-"}</td><td>{d.last_checked_at?new Date(d.last_checked_at).toLocaleString():"-"}</td><td>{d.is_active?"Yes":"No"}</td><td><div className="actions"><button className="iconBtn" title="Single Check" onClick={()=>singleCheck(d)}><RefreshCw size={14}/></button><button className="iconBtn" title="Edit" onClick={()=>editDomain(d)}><Pencil size={14}/></button><button className="iconBtn" title="Active/Pause" onClick={()=>toggleDomain(d)}><Power size={14}/></button><button className="iconBtn danger" title="Delete" onClick={()=>deleteDomain(d)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></section>

    <section className="panel"><h2>Proxy Checker</h2><form onSubmit={addProxy} className="grid"><input placeholder="Name" value={proxy.name} onChange={e=>setProxy({...proxy,name:e.target.value})}/><input placeholder="Provider" value={proxy.provider_name} onChange={e=>setProxy({...proxy,provider_name:e.target.value})}/><input placeholder="Proxy URL" value={proxy.proxy_url} onChange={e=>setProxy({...proxy,proxy_url:e.target.value})}/><select value={proxy.proxy_type} onChange={e=>setProxy({...proxy,proxy_type:e.target.value})}><option value="http">HTTP/HTTPS</option><option value="socks">SOCKS</option></select><button>Add Proxy</button></form><div className="chips">{proxies.map(p=><span key={p.id}>{p.provider_name}: {p.name} · {p.last_health_status||"unknown"}<button className="chipDelete" onClick={()=>deleteProxy(p)}>×</button></span>)}</div></section>

    <section className="panel"><div className="panelHead"><h2>History</h2><button className="smallBtn" onClick={()=>exportCsv("/api/export/results.csv")}><Download size={15}/> CSV</button></div><table><thead><tr><th>Time</th><th>Domain</th><th>Checker</th><th>Status</th><th>HTTP</th><th>Latency</th><th>Reason</th></tr></thead><tbody>{results.map(r=><tr key={r.id}><td>{new Date(r.checked_at).toLocaleString()}</td><td className="domainCell">{r.domain}</td><td>{r.provider_name}</td><td><Badge status={r.status}/></td><td>{r.http_status||"-"}</td><td>{r.latency_ms?`${r.latency_ms}ms`:"-"}</td><td>{r.reason}</td></tr>)}</tbody></table></section>
  </main></div>;
}
function App(){const[checked,setChecked]=useState(false);const[authenticated,setAuthenticated]=useState(false);const[bootError,setBootError]=useState("");async function checkAuth(){try{const me=await api("/api/auth/me");setAuthenticated(Boolean(me.authenticated));}catch(err){setBootError(err.message||"Auth check failed.");setAuthenticated(false);}finally{setChecked(true);}}useEffect(()=>{checkAuth();},[]);if(!checked)return <div className="loading">Loading Domain Radar...</div>;if(!authenticated)return <><Login onLogin={async()=>setAuthenticated(true)}/>{bootError?<div className="bootError">{bootError}</div>:null}</>;return <Dashboard onLogout={()=>setAuthenticated(false)}/>;}
const rootEl=document.getElementById("root"); if(rootEl) createRoot(rootEl).render(<App/>);
